### 몽고db 테스트
GET http://localhost:8100/test-mongo

### 유저 생성1
POST http://localhost:8100/api/v1/users
Content-Type: application/json

{
  "username": "user1",
  "nickname": "user1"
}

### 유저 생성2
POST http://localhost:8100/api/v1/users
Content-Type: application/json

{
  "username": "user2",
  "nickname": "user2"
}

### 채팅방 생성
POST http://localhost:8100/api/v1/chatrooms/create
Content-Type: application/json

{
  "title": "Team Discussion",
  "participants": ["678bb75e49f8de2dbcf39e1c", "678bdb8672191c638735b4e5"]
}

### 채팅방 목록 조회
GET http://localhost:8100/api/v1/chatrooms?
    userId=678bb75e49f8de2dbcf39e1c

### 특정 채팅방의 메시지 목록 조회
GET http://localhost:8100/api/v1/messages/get?
    roomId=678bdba172191c638735b4e6&
    before=2021-08-01T00:00:00Z&
    limit=10


### {"roomId": "678bb9ea49f8de2dbcf39e1e", "senderId": "678bb75e49f8de2dbcf39e1c", "content": "Hello STOMP"}